#logging.level.root: DEBUG
#server.port: 8082
spring:
  main:
    allow-circular-references: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/webshop
#    username: postgres
#    password: testtest

